language: java
deploy:
  provider: heroku
  app: damp-refuge-11636
  api_key:
    secure: QcF8J9WOyfNphf+DiclHhDsFPas05eLWHyQz/+FThaHJljNwNGyt67zh71cQnTO5dMO31cz/8Z72c3Q7wC8IfVqU8ad8vdkYu60EVUeYKtDZPXQx6226R2gm69NIBSdaNJc9PrmbZ5Ep/UivbtAZnfWHDoZ/W/Xnzk1PnEqHgEoa5OSV42u2pJ3l5BnYbf/J/kynTO703PPE0r+UZxv6qHhPG9ZyBUCFq6dmONTcM9dgqO5FhKohGnfLZ9/8Sx94Iju5e9wFxWEWWJM0oQM4eu/m4jtfCneRvICOWlbZPBfTsPSQ4d96J+OKxP84MlIuLhLJ7LTiQYDCQZmuUG0N9U8Bz63yUBZBZokUuTDxXQvmDVS35fC54orQ5EyCdsHYUTcf0nZfW0MUiyUYVBiNee8HKUa4eh4JHUM0JAhDqmdCUZT/3Zs7ap0q7uk6IR+HidnJjTIpjg/uyvYNczYE3WcxnyjprY3+d40F3hPkF4nirnVCPrxz29t0RRxXfYRTKvbZSGPDJ6MLM/qsoxXZrxTo31uOLd4FwxB8kSYvc4uO/Ubwz2502VWsexf5g5EXOvpxA3dMGK/9Q3gNCyYLpAwUd7g887VW6xXm8YNIbB5/LhlEeqIVReeWs+vMAQltf+33CUsIEwTX5b8WJXkxgCtXxVywzw3lQPyurUtfxUI=
